"""초기 224종 가운데 새로 그리는 205종의 표다.

열: id, 영문명, 한글명, 이벤트 그룹, 몸 동작, 활동 시간, 게임 폭(px), 발광 규칙, 방문자 여부, 시점, 생김새 힌트.
- 그룹은 `src/sim/director.ts`의 이벤트가 등장시킬 생물을 고를 때 쓴다. 모든 그룹에 이벤트가 하나 이상 있다.
- 시점(view)은 Codex 프롬프트의 구도다: side(옆, 머리 오른쪽), top(위에서, 머리 오른쪽), flat(바닥에 누워 3/4),
  front(정면), jelly(해파리 정면), upright(곧게 서서 오른쪽), floor(바닥에 놓인 물체), mantle(외투막 끝이 오른쪽).
- 방문자(visitor)는 평소 순환에 나오지 않고 사건 때만 등장한다(대형 고래).
"""

# 이미 만든 20종 중 초기 목록과 같은 종: 원래 이름 -> 현재 id
EXISTING = {
    "Ocellaris clownfish": "clownfish", "Blue tang": "blue-tang", "Yellow tang": "yellow-tang",
    "Moorish idol": "moorish-idol", "Sardine": "sardine", "Moon jelly": "moon-jelly",
    "Pacific sea nettle": "sea-nettle", "Green sea turtle": "green-turtle",
    "Giant oceanic manta ray": "manta-ray", "Hammerhead shark": "hammerhead",
    "Bottlenose dolphin": "dolphin", "Anglerfish": "anglerfish", "Whale shark": "whale-shark",
    "Ocean sunfish": "sunfish", "Oarfish": "oarfish", "Mandarin dragonet": "mandarinfish",
    "Red lionfish": "lionfish", "Giant Pacific octopus": "octopus", "Red coral crab": "red-crab",
}

# 이미 만든 종의 그룹
EXISTING_GROUPS = {
    "clownfish": "clown", "blue-tang": "reef", "yellow-tang": "reef", "moorish-idol": "reef",
    "emperor-angelfish": "reef", "pufferfish": "puffer", "lionfish": "camo", "mandarinfish": "reef",
    "sardine": "school", "seahorse": "seahorse", "moon-jelly": "jelly", "sea-nettle": "jelly",
    "green-turtle": "turtle", "manta-ray": "ray", "hammerhead": "shark", "dolphin": "dolphin",
    "octopus": "ceph", "red-crab": "crust", "anglerfish": "deep", "firefly-squid": "school",
    "whale-shark": "shark", "sunfish": "pelagic", "baby-turtle": "turtle", "oarfish": "deep",
    "diver": "none",
}

N, D, A = "night", "day", "any"

# 생성 결과가 왼쪽을 보는 종. 굽을 때 좌우를 뒤집어 모든 시트가 오른쪽을 보게 한다(검수 후 채운다).
FLIP: set[str] = set()

NEW = [
    # (id, en, ko, group, motion, activity, width, glow, visitor, view, hint)
    ("regal-angelfish", "Regal angelfish", "리갈엔젤피시", "reef", "fish", D, 32, None, False, "side", "orange-yellow body with blue-white vertical stripes"),
    ("copperband-butterflyfish", "Copperband butterflyfish", "코퍼밴드나비고기", "reef", "fish", D, 30, None, False, "side", "white body with copper-orange vertical bands and a long snout"),
    ("spotfin-lionfish", "Spotfin lionfish", "스팟핀쏠배감펭", "camo", "fish", A, 34, None, False, "side", "red-brown banded body with big spotted fan pectoral fins"),
    ("spiny-porcupinefish", "Spiny porcupinefish", "가시복", "puffer", "puff", A, 30, None, False, "side", "tan body covered with spines and dark spots, big eyes"),
    ("tiger-tail-seahorse", "Tiger tail seahorse", "호랑이꼬리해마", "seahorse", "hover", A, 18, None, False, "upright", "yellow seahorse with black tiger stripes on its tail"),
    ("blue-moon-jelly", "Blue moon jelly", "푸른보름달해파리", "jelly", "jelly", A, 30, "all", False, "jelly", "translucent blue bell with four pale rings"),
    ("california-two-spot-octopus", "California two-spot octopus", "두점박이문어", "ceph", "octopus", N, 32, None, False, "front", "brown octopus with two blue eye-spots"),
    ("olive-ridley-sea-turtle", "Olive ridley sea turtle", "올리브각시바다거북", "turtle", "glide", D, 54, None, False, "side", "olive green heart-shaped shell"),
    ("reef-manta-ray", "Reef manta ray", "암초쥐가오리", "ray", "flap", A, 78, None, False, "top", "black back with white shoulder patches"),
    ("blue-whale", "Blue whale", "흰긴수염고래", "whale", "giant", A, 260, None, True, "side", "enormous blue-grey mottled body, small dorsal fin"),
    ("pacific-white-sided-dolphin", "Pacific white-sided dolphin", "낫돌고래", "dolphin", "giant", D, 72, None, False, "side", "black back, grey side stripes, white belly"),
    ("tomato-clownfish", "Tomato clownfish", "토마토흰동가리", "clown", "fish", D, 26, None, False, "side", "red-orange body with one white head band"),
    ("maroon-clownfish", "Maroon clownfish", "마룬흰동가리", "clown", "fish", D, 28, None, False, "side", "dark maroon body with three thin gold bands"),
    ("black-clownfish", "Black clownfish", "검은흰동가리", "clown", "fish", D, 26, None, False, "side", "black body with three white bands"),
    ("pink-skunk-clownfish", "Pink skunk clownfish", "핑크스컹크흰동가리", "clown", "fish", D, 26, None, False, "side", "pale pink-orange body with a white stripe along the back"),
    ("powder-blue-tang", "Powder blue tang", "파우더블루탱", "reef", "fish", D, 30, None, False, "side", "powder blue oval body, black face, yellow dorsal fin"),
    ("achilles-tang", "Achilles tang", "아킬레스탱", "reef", "fish", D, 30, None, False, "side", "black body with an orange teardrop spot near the tail"),
    ("sailfin-tang", "Sailfin tang", "세일핀탱", "reef", "fish", D, 32, None, False, "side", "tall sail-like fins with brown and yellow vertical bands"),
    ("orange-shoulder-tang", "Orange shoulder tang", "오렌지숄더탱", "reef", "fish", D, 32, None, False, "side", "grey body with a bright orange shoulder patch"),
    ("queen-angelfish", "Queen angelfish", "퀸엔젤피시", "reef", "fish", D, 34, None, False, "side", "blue-green body with yellow fins and a blue crown spot"),
    ("flame-angelfish", "Flame angelfish", "플레임엔젤피시", "reef", "fish", D, 24, None, False, "side", "bright red-orange body with black vertical bars"),
    ("coral-beauty-angelfish", "Coral beauty angelfish", "코랄뷰티엔젤피시", "reef", "fish", D, 24, None, False, "side", "deep blue body with an orange center"),
    ("french-angelfish", "French angelfish", "프렌치엔젤피시", "reef", "fish", D, 34, None, False, "side", "black body with yellow-rimmed scales"),
    ("raccoon-butterflyfish", "Raccoon butterflyfish", "라쿤나비고기", "reef", "fish", D, 28, None, False, "side", "yellow body with a black raccoon mask over the eye"),
    ("threadfin-butterflyfish", "Threadfin butterflyfish", "실지느러미나비고기", "reef", "fish", D, 28, None, False, "side", "white and yellow body with diagonal lines and a thread-like fin"),
    ("longnose-butterflyfish", "Longnose butterflyfish", "롱노즈나비고기", "reef", "fish", D, 28, None, False, "side", "bright yellow body with a long thin snout"),
    ("chevron-butterflyfish", "Chevron butterflyfish", "셰브론나비고기", "reef", "fish", D, 26, None, False, "side", "white body with a chevron pattern and orange tail"),
    ("fairy-wrasse", "Fairy wrasse", "요정놀래기", "reef", "fish", D, 24, None, False, "side", "rainbow purple-orange slender fish"),
    ("humphead-wrasse", "Humphead wrasse", "나폴레옹피시", "bigreef", "fish", D, 68, None, False, "side", "huge green-blue wrasse with a bump on its head and thick lips"),
    ("cleaner-wrasse", "Cleaner wrasse", "청줄청소놀래기", "reef", "fish", D, 20, None, False, "side", "slender fish with a black stripe from snout to tail, blue back"),
    ("bannerfish", "Bannerfish", "두동가리돔", "reef", "fish", D, 28, None, False, "side", "white and black bands with a long white banner fin"),
    ("foxface-rabbitfish", "Foxface rabbitfish", "여우얼굴독가시치", "reef", "fish", D, 30, None, False, "side", "yellow body with a black and white fox-like face"),
    ("spotted-rabbitfish", "Spotted rabbitfish", "점박이독가시치", "reef", "fish", D, 30, None, False, "side", "olive body covered with pale spots"),
    ("purple-firefish", "Purple firefish", "퍼플파이어피시", "reef", "fish", D, 20, None, False, "side", "slender fish with purple head and tall dorsal spine"),
    ("red-firefish", "Red firefish", "레드파이어피시", "reef", "fish", D, 20, None, False, "side", "white-yellow front fading to red tail, tall dorsal spine"),
    ("yellow-watchman-goby", "Yellow watchman goby", "노랑망둑", "reef", "fish", D, 20, None, False, "side", "yellow goby with blue dots"),
    ("neon-goby", "Neon goby", "네온망둑", "reef", "fish", D, 16, None, False, "side", "tiny black fish with a neon blue stripe"),
    ("pajama-cardinalfish", "Pajama cardinalfish", "파자마카디널", "reef", "fish", N, 20, None, False, "side", "yellow face, dark band, red polka-dot rear"),
    ("banggai-cardinalfish", "Banggai cardinalfish", "방가이카디널", "reef", "fish", D, 22, None, False, "side", "silver body with black bars and white dots, long fins"),
    ("blue-green-chromis", "Blue-green chromis", "청록자리돔", "school", "school", D, 14, None, False, "side", "small blue-green shimmering fish"),
    ("sunset-anthias", "Sunset anthias", "선셋안티아스", "reef", "fish", D, 22, None, False, "side", "orange-pink body with a yellow stripe"),
    ("anchovy", "Anchovy", "멸치", "school", "school", D, 14, None, False, "side", "tiny silver fish with a green back"),
    ("atlantic-herring", "Atlantic herring", "청어", "school", "school", D, 18, None, False, "side", "silver fish with a blue-green back"),
    ("pacific-mackerel", "Pacific mackerel", "고등어", "school", "school", D, 22, None, False, "side", "green-blue back with wavy dark stripes, silver belly"),
    ("bluefin-tuna", "Bluefin tuna", "참다랑어", "pelagic", "giant", D, 90, None, False, "side", "torpedo body, dark blue back, silver belly, yellow finlets"),
    ("yellowfin-tuna", "Yellowfin tuna", "황다랑어", "pelagic", "giant", D, 84, None, False, "side", "torpedo body with long yellow fins"),
    ("skipjack-tuna", "Skipjack tuna", "가다랑어", "pelagic", "fish", D, 54, None, False, "side", "stripes on the silver belly, dark back"),
    ("mahi-mahi", "Mahi mahi", "만새기", "pelagic", "fish", D, 68, None, False, "side", "gold-green body with a blunt forehead and long dorsal fin"),
    ("flying-fish", "Flying fish", "날치", "pelagic", "fish", D, 36, None, False, "side", "blue silver fish with huge wing-like pectoral fins spread"),
    ("needlefish", "Needlefish", "동갈치", "pelagic", "fish", D, 44, None, False, "side", "very thin silver fish with long needle jaws"),
    ("barracuda", "Barracuda", "창꼬치", "pelagic", "fish", A, 64, None, False, "side", "long silver fish with dark bars and big teeth"),
    ("swordfish", "Swordfish", "황새치", "pelagic", "giant", A, 110, None, False, "side", "dark purple-grey body with a long flat sword bill"),
    ("opah-moonfish", "Opah moonfish", "붉평치", "pelagic", "fish", A, 56, None, False, "side", "round silver-pink body with white spots and red fins"),
    ("giant-trevally", "Giant trevally", "무명갈전갱이", "pelagic", "fish", D, 60, None, False, "side", "silver-grey deep body, steep forehead"),
    ("blue-marlin", "Blue marlin", "청새치", "pelagic", "giant", D, 120, None, False, "side", "cobalt blue back, long spear bill, tall dorsal fin"),
    ("great-white-shark", "Great white shark", "백상아리", "shark", "giant", A, 130, None, False, "side", "grey back, white belly, big teeth"),
    ("tiger-shark", "Tiger shark", "뱀상어", "shark", "giant", A, 120, None, False, "side", "grey shark with dark tiger stripes"),
    ("blacktip-reef-shark", "Blacktip reef shark", "흑기흉상어", "shark", "giant", D, 88, None, False, "side", "slim shark with black fin tips"),
    ("whitetip-reef-shark", "Whitetip reef shark", "백기흉상어", "shark", "giant", N, 88, None, False, "side", "slim grey shark with white fin tips"),
    ("zebra-shark", "Zebra shark", "얼룩말상어", "bottomshark", "giant", A, 90, None, False, "side", "tan body with dark spots and ridges, very long tail"),
    ("leopard-shark", "Leopard shark", "레오파드상어", "bottomshark", "giant", A, 84, None, False, "side", "grey body with dark saddle spots"),
    ("nurse-shark", "Nurse shark", "너스상어", "bottomshark", "giant", N, 96, None, False, "side", "yellow-brown bottom shark with barbels"),
    ("epaulette-shark", "Epaulette shark", "견장상어", "bottomshark", "creep", N, 50, None, False, "side", "slim spotted shark with big black shoulder spots, walks on fins"),
    ("thresher-shark", "Thresher shark", "환도상어", "shark", "giant", A, 120, None, False, "side", "purple-grey shark with an extremely long upper tail lobe"),
    ("mako-shark", "Mako shark", "청상아리", "shark", "giant", A, 110, None, False, "side", "metallic blue sleek shark with pointed snout"),
    ("sand-tiger-shark", "Sand tiger shark", "모래뱀상어", "shark", "giant", N, 108, None, False, "side", "brown shark with ragged teeth sticking out"),
    ("greenland-shark", "Greenland shark", "그린란드상어", "deep", "giant", N, 128, None, False, "side", "stout slow grey-brown shark with tiny eyes"),
    ("spotted-eagle-ray", "Spotted eagle ray", "점박이매가오리", "ray", "flap", D, 70, None, False, "top", "dark blue back covered with white spots, long tail"),
    ("cownose-ray", "Cownose ray", "소코가오리", "ray", "flap", D, 56, None, False, "top", "brown ray with a notched cow-like head"),
    ("bat-ray", "Bat ray", "박쥐가오리", "ray", "flap", A, 60, None, False, "top", "dark brown ray with a raised head"),
    ("electric-ray", "Electric ray", "전기가오리", "ray", "flap", N, 44, None, False, "top", "round brown disc-shaped ray with a short thick tail"),
    ("humpback-whale", "Humpback whale", "혹등고래", "whale", "giant", A, 250, None, True, "side", "dark body, knobby head, very long white flippers"),
    ("orca", "Orca", "범고래", "whale", "giant", A, 150, None, True, "side", "black and white killer whale with tall dorsal fin"),
    ("sperm-whale", "Sperm whale", "향유고래", "whale", "giant", A, 240, None, True, "side", "grey whale with a huge boxy head"),
    ("beluga-whale", "Beluga whale", "흰고래", "whale", "giant", A, 130, None, True, "side", "all-white whale with a round melon forehead"),
    ("narwhal", "Narwhal", "일각고래", "whale", "giant", A, 140, None, True, "side", "mottled grey whale with a long spiral tusk"),
    ("gray-whale", "Gray whale", "귀신고래", "whale", "giant", A, 230, None, True, "side", "grey whale mottled with white barnacle patches"),
    ("bowhead-whale", "Bowhead whale", "북극고래", "whale", "giant", A, 240, None, True, "side", "dark whale with a huge bow-shaped white chin"),
    ("minke-whale", "Minke whale", "밍크고래", "whale", "giant", A, 200, None, True, "side", "sleek dark grey whale with white flipper bands"),
    ("spinner-dolphin", "Spinner dolphin", "스피너돌고래", "dolphin", "giant", D, 68, None, False, "side", "slender three-toned grey dolphin with a long beak"),
    ("harbor-porpoise", "Harbor porpoise", "쥐돌고래", "dolphin", "giant", D, 58, None, False, "side", "small stocky dark grey porpoise without a beak"),
    ("vaquita", "Vaquita", "바키타", "dolphin", "giant", D, 52, None, False, "side", "tiny grey porpoise with dark eye rings and lips"),
    ("sea-otter", "Sea otter", "해달", "pinniped", "glide", D, 48, None, False, "side", "brown furry otter swimming, whiskers"),
    ("harbor-seal", "Harbor seal", "잔점박이물범", "pinniped", "glide", A, 62, None, False, "side", "spotted grey seal swimming"),
    ("california-sea-lion", "California sea lion", "캘리포니아바다사자", "pinniped", "glide", D, 70, None, False, "side", "sleek brown sea lion with flippers"),
    ("walrus", "Walrus", "바다코끼리", "pinniped", "glide", A, 88, None, False, "side", "big brown walrus with long white tusks and whiskers"),
    ("lions-mane-jelly", "Lion's mane jelly", "사자갈기해파리", "jelly", "jelly", A, 36, None, False, "jelly", "huge red-orange bell with masses of long hair-like tentacles"),
    ("compass-jelly", "Compass jelly", "컴퍼스해파리", "jelly", "jelly", A, 30, None, False, "jelly", "cream bell with brown V-shaped compass markings"),
    ("blue-blubber-jelly", "Blue blubber jelly", "블루블러버해파리", "jelly", "jelly", A, 30, None, False, "jelly", "firm blue bell with frilly oral arms"),
    ("flower-hat-jelly", "Flower hat jelly", "꽃모자해파리", "jelly", "jelly", N, 30, "all", False, "jelly", "clear bell with glowing neon pink and green tentacles curled on top"),
    ("upside-down-jelly", "Upside-down jelly", "거꾸로해파리", "jelly", "jelly", A, 28, None, False, "jelly", "flat bell with bushy greenish oral arms"),
    ("box-jellyfish", "Box jellyfish", "상자해파리", "jelly", "jelly", A, 30, None, False, "jelly", "transparent cube-shaped bell with long tentacles from the corners"),
    ("blue-ringed-octopus", "Blue-ringed octopus", "파란고리문어", "ceph", "octopus", N, 26, "blue", False, "front", "small yellow octopus covered in bright blue rings"),
    ("dumbo-octopus", "Dumbo octopus", "덤보문어", "deep", "octopus", N, 32, None, False, "front", "pale pink octopus with ear-like fins on its head"),
    ("blanket-octopus", "Blanket octopus", "담요문어", "ceph", "octopus", A, 40, None, False, "front", "octopus with a long flowing iridescent purple blanket web"),
    ("common-cuttlefish", "Common cuttlefish", "갑오징어", "ceph", "squid", A, 38, None, False, "mantle", "brown zebra-patterned cuttlefish with wavy side fins"),
    ("flamboyant-cuttlefish", "Flamboyant cuttlefish", "화려한갑오징어", "ceph", "squid", D, 30, None, False, "mantle", "small cuttlefish in purple, yellow and red colors"),
    ("reef-squid", "Reef squid", "흰오징어", "ceph", "squid", N, 34, None, False, "mantle", "translucent brown squid with fins along the mantle"),
    ("vampire-squid", "Vampire squid", "흡혈오징어", "deep", "octopus", N, 34, "blue", False, "front", "dark red cephalopod with a webbed cloak and glowing blue eyes"),
    ("giant-clam", "Giant clam", "대왕조개", "sessile", "sessile", A, 36, None, False, "floor", "huge clam with wavy shell open, vivid blue-purple mantle"),
    ("scallop", "Scallop", "가리비", "sessile", "sessile", A, 22, None, False, "floor", "fan-shaped ridged shell lying on the sand, tiny blue eyes on the edge"),
    ("abalone", "Abalone", "전복", "sessile", "sessile", A, 24, None, False, "floor", "ear-shaped rough shell with holes, lying on a rock"),
    ("chambered-nautilus", "Chambered nautilus", "앵무조개", "deep", "squid", N, 30, None, False, "side", "white shell with brown stripes, tentacles pointing to the RIGHT"),
    ("king-crab", "King crab", "왕게", "crust", "crawl", A, 44, None, False, "front", "big spiky red king crab with long legs"),
    ("coconut-crab", "Coconut crab", "야자집게", "crust", "crawl", A, 40, None, False, "front", "huge purple-orange crab with big claws"),
    ("hermit-crab", "Hermit crab", "소라게", "crust", "creep", A, 24, None, False, "side", "red hermit crab inside a spiral shell, walking to the RIGHT"),
    ("horseshoe-crab", "Horseshoe crab", "투구게", "crust", "creep", A, 36, None, False, "flat", "brown horseshoe-shaped shell with a spike tail"),
    ("spiny-lobster", "Spiny lobster", "닭새우", "crust", "creep", N, 44, None, False, "side", "orange-red spiny lobster with long antennae, walking to the RIGHT"),
    ("mantis-shrimp", "Mantis shrimp", "갯가재", "crust", "creep", A, 30, None, False, "side", "rainbow green-orange mantis shrimp with big eyes"),
    ("cleaner-shrimp", "Cleaner shrimp", "청소새우", "crust", "creep", A, 22, None, False, "side", "red and white striped shrimp with long white antennae"),
    ("pistol-shrimp", "Pistol shrimp", "딱총새우", "crust", "creep", A, 20, None, False, "side", "orange shrimp with one oversized snapping claw"),
    ("red-sea-star", "Red sea star", "빨강불가사리", "sessile", "sessile", A, 24, None, False, "floor", "bright red five-armed starfish"),
    ("sunflower-sea-star", "Sunflower sea star", "해바라기불가사리", "sessile", "sessile", A, 32, None, False, "floor", "orange-purple starfish with many arms"),
    ("purple-sea-urchin", "Purple sea urchin", "보라성게", "sessile", "sessile", A, 22, None, False, "floor", "round purple urchin covered in spines"),
    ("sea-cucumber", "Sea cucumber", "해삼", "sessile", "creep", A, 30, None, False, "side", "bumpy brown-orange sea cucumber crawling to the RIGHT"),
    ("black-dragonfish", "Black dragonfish", "검은용고기", "deep", "eel", N, 46, "bright", False, "side", "long black eel-like fish with fangs, glowing chin barbel and light spots"),
    ("viperfish", "Viperfish", "독사고기", "deep", "fish", N, 40, "bright", False, "side", "dark fish with huge needle fangs and glowing dots along its belly"),
    ("silver-hatchetfish", "Silver hatchetfish", "은도끼고기", "school", "school", N, 16, "bright", False, "side", "tiny hatchet-shaped silver fish with glowing belly dots"),
    ("lanternfish", "Lanternfish", "샛비늘치", "school", "school", N, 16, "bright", False, "side", "small dark fish with glowing blue light spots"),
    ("flashlight-fish", "Flashlight fish", "등불고기", "deep", "fish", N, 28, "bright", False, "side", "black fish with a bright glowing light organ under its eye"),
    ("fangtooth", "Fangtooth", "송곳니고기", "deep", "fish", N, 30, None, False, "side", "dark brown fish with huge head and long fangs"),
    ("gulper-eel", "Gulper eel", "풍선장어", "deep", "eel", N, 60, None, False, "side", "black eel with an enormous pelican-like mouth and a thin whip tail"),
    ("barreleye-fish", "Barreleye fish", "통안어", "deep", "fish", N, 32, None, False, "side", "fish with a transparent dome head and green tube eyes"),
    ("tripod-fish", "Tripod fish", "삼발이고기", "deep", "creep", N, 38, None, False, "side", "pale fish standing on three long fin rays like a tripod"),
    ("giant-isopod", "Giant isopod", "대왕구족충", "deep", "creep", N, 30, None, False, "side", "big grey segmented pill-bug crustacean crawling to the RIGHT"),
    ("sea-angel", "Sea angel", "바다천사", "deep", "hover", N, 18, "all", False, "upright", "translucent glowing sea slug with two wing-like flaps and an orange center"),
    ("rainbow-comb-jelly", "Rainbow comb jelly", "무지개빗해파리", "jelly", "jelly", N, 26, "all", False, "jelly", "clear oval comb jelly with rainbow shimmering comb rows"),
    ("siphonophore", "Siphonophore", "관해파리", "jelly", "eel", N, 56, "all", False, "side", "long glowing chain of translucent jelly bells, horizontal, pointing RIGHT"),
    ("atolla-jelly", "Atolla jelly", "아톨라해파리", "deep", "jelly", N, 30, "all", False, "jelly", "deep red crown-shaped jelly with glowing blue ring"),
    ("glass-squid", "Glass squid", "유리오징어", "deep", "squid", N, 28, "all", False, "mantle", "transparent barrel-shaped squid with glowing eyes"),
    ("leafy-seadragon", "Leafy seadragon", "나뭇잎해룡", "seahorse", "hover", A, 40, None, False, "side", "yellow-green seahorse relative covered in leafy appendages, head pointing RIGHT"),
    ("weedy-seadragon", "Weedy seadragon", "풀잎해룡", "seahorse", "hover", A, 38, None, False, "side", "red body with yellow spots and small weedy appendages, head pointing RIGHT"),
    ("pygmy-seahorse", "Pygmy seahorse", "피그미해마", "seahorse", "hover", A, 12, None, False, "upright", "tiny pink bumpy seahorse"),
    ("longsnout-seahorse", "Longsnout seahorse", "주둥이긴해마", "seahorse", "hover", A, 20, None, False, "upright", "slender orange seahorse with a long snout"),
    ("pipefish", "Pipefish", "실고기", "seahorse", "eel", A, 34, None, False, "side", "very thin straight fish with a tube snout, banded"),
    ("ornate-ghost-pipefish", "Ornate ghost pipefish", "유령실고기", "seahorse", "hover", A, 24, None, False, "side", "frilly lacy red-white ghost pipefish, head pointing RIGHT"),
    ("seamoth", "Seamoth", "바다나방", "camo", "creep", A, 22, None, False, "flat", "small brown bottom fish with wing-like pectoral fins"),
    ("flying-gurnard", "Flying gurnard", "쭉지성대", "camo", "creep", D, 40, None, False, "side", "bottom fish with huge blue-spotted wing fins spread out"),
    ("zebra-moray-eel", "Zebra moray eel", "얼룩말곰치", "eel", "eel", N, 60, None, False, "side", "dark brown eel with white zebra stripes"),
    ("snowflake-moray-eel", "Snowflake moray eel", "눈송이곰치", "eel", "eel", N, 56, None, False, "side", "white eel with black and yellow snowflake spots"),
    ("ribbon-eel", "Ribbon eel", "리본장어", "eel", "eel", N, 56, None, False, "side", "thin electric blue eel with a yellow fin and flared nostrils"),
    ("wolf-eel", "Wolf eel", "늑대장어", "eel", "eel", N, 64, None, False, "side", "grey spotted eel with a big grumpy face"),
    ("garden-eel", "Garden eel", "정원장어", "eel", "sessile", D, 12, None, False, "upright", "thin spotted eel sticking straight up out of the sand"),
    ("conger-eel", "Conger eel", "붕장어", "eel", "eel", N, 64, None, False, "side", "long grey-brown eel with a pale belly"),
    ("pacific-hagfish", "Pacific hagfish", "먹장어", "deep", "eel", N, 44, None, False, "side", "pink-grey slimy eel-like fish with barbels"),
    ("red-lipped-batfish", "Red-lipped batfish", "붉은입술부치", "camo", "creep", A, 30, None, False, "side", "brown bottom fish with bright red lips, walking on its fins"),
    ("hairy-frogfish", "Hairy frogfish", "털씬벵이", "camo", "hover", A, 30, None, False, "side", "round yellow frogfish covered in hair-like spinules"),
    ("reef-stonefish", "Reef stonefish", "쑤기미", "camo", "creep", A, 32, None, False, "side", "lumpy grey-brown camouflaged rock-like fish"),
    ("stargazer-fish", "Stargazer fish", "얼룩통구멍", "camo", "creep", N, 34, None, False, "side", "fish with upward eyes and mouth half buried in sand"),
    ("scorpionfish", "Scorpionfish", "쏨뱅이", "camo", "fish", A, 32, None, False, "side", "red mottled spiny fish"),
    ("sea-toadfish", "Sea toadfish", "두꺼비고기", "camo", "creep", N, 32, None, False, "side", "brown flat-headed toadfish with a wide mouth"),
    ("flathead-fish", "Flathead fish", "양태", "camo", "creep", A, 40, None, False, "side", "flat sandy brown fish with a wide flat head"),
    ("clown-triggerfish", "Clown triggerfish", "광대쥐치", "puffer", "fish", D, 34, None, False, "side", "black body with big white spots and a yellow leopard saddle"),
    ("orange-spotted-filefish", "Orange-spotted filefish", "오렌지점쥐치", "puffer", "fish", D, 28, None, False, "side", "green body with orange spots and a pointed snout"),
    ("yellow-boxfish", "Yellow boxfish", "노랑거북복", "puffer", "puff", D, 26, None, False, "side", "bright yellow cube-shaped fish with black dots"),
    ("longhorn-cowfish", "Longhorn cowfish", "뿔거북복", "puffer", "puff", D, 30, None, False, "side", "yellow boxy fish with two horns on the head and a long tail"),
    ("bumphead-parrotfish", "Bumphead parrotfish", "혹돔", "bigreef", "fish", D, 70, None, False, "side", "big green parrotfish with a bumpy forehead and beak"),
    ("zebra-surgeonfish", "Zebra surgeonfish", "얼룩말쥐돔", "reef", "fish", D, 30, None, False, "side", "pale body with thin black zebra bars"),
    ("coral-grouper", "Coral grouper", "산호바리", "bigreef", "fish", A, 50, None, False, "side", "red grouper covered in small blue spots"),
    ("giant-sea-bass", "Giant sea bass", "자이언트농어", "bigreef", "giant", A, 90, None, False, "side", "huge dark grey-brown bass with black spots"),
    ("arctic-cod", "Arctic cod", "북극대구", "cold", "fish", A, 36, None, False, "side", "brown speckled cod with a chin barbel"),
    ("antarctic-icefish", "Antarctic icefish", "남극빙어", "cold", "fish", A, 38, None, False, "side", "pale translucent fish with a crocodile-like snout"),
    ("pacific-spiny-lumpsucker", "Pacific spiny lumpsucker", "도치", "cold", "hover", A, 20, None, False, "side", "tiny round green ball-shaped fish with bumps"),
    ("snailfish", "Snailfish", "꼼치", "deep", "fish", N, 30, None, False, "side", "pale pink gelatinous tadpole-shaped fish"),
    ("atlantic-halibut", "Atlantic halibut", "대서양넙치", "camo", "creep", A, 60, None, False, "flat", "large brown flatfish with both eyes on one side"),
    ("peacock-flounder", "Peacock flounder", "공작가자미", "camo", "creep", A, 36, None, False, "flat", "flatfish covered with bright blue ring spots"),
    ("dover-sole", "Dover sole", "도버서대기", "camo", "creep", A, 32, None, False, "flat", "oval brown sole flatfish"),
    ("turbot", "Turbot", "터봇", "camo", "creep", A, 38, None, False, "flat", "round speckled brown flatfish"),
    ("atlantic-salmon", "Atlantic salmon", "대서양연어", "cold", "fish", A, 52, None, False, "side", "silver salmon with small black spots"),
    ("steelhead-trout", "Steelhead trout", "무지개송어", "cold", "fish", A, 46, None, False, "side", "silver trout with a pink rainbow stripe"),
    ("striped-bass", "Striped bass", "줄무늬농어", "cold", "fish", A, 50, None, False, "side", "silver bass with dark horizontal stripes"),
    ("black-sea-bass", "Black sea bass", "검은바다농어", "cold", "fish", A, 40, None, False, "side", "dark blue-black bass with pale scale pattern"),
    ("red-snapper", "Red snapper", "붉은퉁돔", "pelagic", "fish", D, 44, None, False, "side", "pinkish-red snapper with red eyes"),
    ("yellowtail-amberjack", "Yellowtail amberjack", "방어", "pelagic", "fish", D, 58, None, False, "side", "silver-blue body with a yellow stripe and yellow tail"),
    ("bigeye-tuna", "Bigeye tuna", "눈다랑어", "pelagic", "giant", A, 86, None, False, "side", "plump tuna with very big eyes, dark blue back"),
    ("bluefish", "Bluefish", "게르치", "pelagic", "fish", D, 44, None, False, "side", "blue-green back with a silver belly, sharp teeth"),
    ("spotted-wobbegong", "Spotted wobbegong", "점박이수염상어", "bottomshark", "creep", N, 70, None, False, "flat", "flat carpet shark with ornate brown pattern and frilly beard"),
    ("horn-shark", "Horn shark", "괭이상어", "bottomshark", "creep", N, 50, None, False, "side", "brown shark with dark spots and ridges over the eyes"),
    ("swell-shark", "Swell shark", "두툽상어", "bottomshark", "creep", N, 50, None, False, "side", "stout brown shark with dark saddle blotches"),
    ("sawfish", "Sawfish", "톱가오리", "ray", "giant", A, 110, None, False, "side", "long olive ray-shark with a flat toothed saw snout"),
    ("shovelnose-guitarfish", "Shovelnose guitarfish", "삽코가래상어", "ray", "giant", A, 62, None, False, "side", "sandy guitar-shaped ray with a shovel nose"),
    ("southern-stingray", "Southern stingray", "남방노랑가오리", "ray", "flap", A, 56, None, False, "top", "grey-brown diamond stingray with a long whip tail"),
    ("ornate-eagle-ray", "Ornate eagle ray", "장식매가오리", "ray", "flap", A, 70, None, False, "top", "eagle ray with ornate dark lines on a pale back"),
    ("hawksbill-sea-turtle", "Hawksbill sea turtle", "매부리바다거북", "turtle", "glide", D, 56, None, False, "side", "turtle with beautiful amber tortoiseshell and hawk-like beak"),
    ("leatherback-sea-turtle", "Leatherback sea turtle", "장수거북", "turtle", "glide", A, 76, None, False, "side", "huge dark turtle with ridged leathery shell"),
    ("loggerhead-sea-turtle", "Loggerhead sea turtle", "붉은바다거북", "turtle", "glide", A, 62, None, False, "side", "reddish-brown shell turtle with a big head"),
    ("dugong", "Dugong", "듀공", "pinniped", "glide", D, 88, None, False, "side", "grey sea cow with a fluked tail and a down-turned snout"),
    ("west-indian-manatee", "West Indian manatee", "서인도매너티", "pinniped", "glide", D, 100, None, False, "side", "chubby grey sea cow with a paddle tail"),
    ("steller-sea-lion", "Steller sea lion", "큰바다사자", "pinniped", "glide", A, 84, None, False, "side", "large tan sea lion with a thick neck"),
    ("marine-iguana", "Marine iguana", "바다이구아나", "pinniped", "glide", D, 44, None, False, "side", "black spiky iguana swimming with its tail"),
    ("chromatic-nudibranch", "Chromatic nudibranch", "갯민숭달팽이", "nudi", "creep", A, 20, None, False, "side", "purple-blue sea slug with orange gills, crawling to the RIGHT"),
    ("spanish-dancer-nudibranch", "Spanish dancer nudibranch", "스페인댄서", "nudi", "hover", A, 30, None, False, "side", "red frilly sea slug swimming like a flamenco skirt"),
    ("blue-dragon-sea-slug", "Blue dragon sea slug", "푸른갯민숭이", "nudi", "hover", A, 20, None, False, "flat", "tiny blue and silver dragon-shaped sea slug with finger-like arms"),
    ("california-sea-hare", "California sea hare", "군소", "nudi", "creep", A, 30, None, False, "side", "large red-brown sea slug with rabbit-ear tentacles"),
    ("christmas-tree-worm", "Christmas tree worm", "크리스마스트리웜", "sessile", "sessile", A, 14, None, False, "floor", "two colorful spiral christmas-tree plumes on a coral lump"),
    ("feather-duster-worm", "Feather duster worm", "깃털꽃갯지렁이", "sessile", "sessile", A, 18, None, False, "floor", "tube worm with a feathery fan crown on top"),
    ("giant-tube-worm", "Giant tube worm", "거대관벌레", "sessile", "sessile", A, 22, None, False, "floor", "cluster of white tubes with bright red plumes"),
    ("pink-sea-anemone", "Pink sea anemone", "분홍말미잘", "sessile", "sessile", A, 26, None, False, "floor", "pink anemone with many waving tentacles"),
    ("porcelain-crab", "Porcelain crab", "도자기게", "crust", "crawl", A, 18, None, False, "front", "small speckled crab with feathery mouth fans"),
    ("decorator-crab", "Decorator crab", "꾸밈게", "crust", "crawl", A, 24, None, False, "front", "crab covered in bits of seaweed and sponge"),
    ("arrow-crab", "Arrow crab", "화살게", "crust", "crawl", A, 22, None, False, "front", "spidery crab with a pointed head and long thin legs"),
    ("brittle-star", "Brittle star", "거미불가사리", "sessile", "sessile", A, 26, None, False, "floor", "starfish with five long thin wiggly arms"),
    ("sand-dollar", "Sand dollar", "연잎성게", "sessile", "sessile", A, 18, None, False, "floor", "flat round grey disc with a five-petal pattern"),
    ("feather-star", "Feather star", "갯고사리", "sessile", "sessile", A, 26, None, False, "floor", "colorful crinoid with feathery arms"),
    ("sea-pen", "Sea pen", "바다조름", "sessile", "sessile", A, 16, None, False, "upright", "orange feather-shaped colony standing out of the sand"),
    # 사용자 요청으로 추가한 종(초기 224종 밖).
    ("elephant-fish", "Elephant fish", "코끼리물고기", "reef", "fish", A, 40, None, False, "side", "slender dark grey-brown body with a very long downward-curving trunk-like snout"),
]

VIEWS = {
    "side": "Strict side view profile, head and face pointing to the RIGHT edge of the image, tail on the LEFT, body horizontal.",
    "top": "Seen from directly above (top-down view), gliding horizontally to the RIGHT: head at the RIGHT edge, both wings spread toward the TOP and BOTTOM of the image, tail trailing to the LEFT.",
    "flat": "Lying on the sea floor, seen from slightly above at a 3/4 angle, head pointing to the RIGHT edge of the image.",
    "front": "Front view facing the viewer, symmetric.",
    "jelly": "Front view, bell on top, tentacles hanging straight down.",
    "upright": "Side view, standing upright vertically, facing RIGHT.",
    "floor": "Resting on the sea floor, seen from the side and slightly above, centered.",
    "mantle": "Side view swimming horizontally: its pointed mantle tip points to the RIGHT edge of the image and its arms trail behind to the LEFT.",
}


def prompt(entry: tuple) -> str:
    _, en, _, _, _, _, _, _, _, view, hint = entry
    return f"a cute {en.lower()} ({hint}). {VIEWS[view]}"
